# Generated by Django 4.1 on 2022-09-17 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='display',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Birthdate', models.CharField(max_length=200)),
                ('adhaar', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('specialization', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='photo')),
            ],
            options={
                'db_table': 'admin',
            },
        ),
    ]
