# Generated by Django 4.1 on 2022-09-17 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='display',
            table='form_info',
        ),
    ]
