# Generated by Django 4.1 on 2022-09-17 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_alter_display_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='display',
            table='admin',
        ),
    ]
