# Generated by Django 4.1 on 2022-09-17 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_alter_display_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='display',
            options={'managed': False},
        ),
    ]
